permissions:
  contents: read
name: nativejs-test-trigger

on:
  push:
    branches: [ main, develop, 'sprint/**', 'release/**' ]
  pull_request:
    branches: [ main, develop, 'sprint/**', 'release/**' ]

jobs:
  trigger-nativejs-l1:
    uses: ./.github/workflows/L1-tests.yml
    with:
      caller_source: local

  trigger-nativejs-l2:
    uses: ./.github/workflows/L2-tests.yml
    with:
      caller_source: local

  trigger-nativejs-l2-oop:
    uses: ./.github/workflows/L2-tests-oop.yml
    with:
      caller_source: local
